#!/usr/bin/env bash

export CONTECO_LABEL="package.kz_server - ModEco"
export CONTECO_DESCRIPTION="Modeco kafka server module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="kz_server"
export CONTECO_TAG="5.4.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
