#!/usr/bin/env bash


prefix="package_$2"

if [[ "_kafka_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _kafka_secrets_volume
	fi
	
if [[ "_kafka_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _kafka_data_volume
	fi
	
if [[ "_zookeeper_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _zookeeper_secrets_volume
	fi
	
if [[ "_zookeeper_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _zookeeper_data_volume
	fi
	
if [[ "_zookeeper_log_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create _zookeeper_log_volume
	fi
	
