#!/usr/bin/env bash


prefix="package_kz_server_$2"

if [[ "package_kz_server_kz_server_kafka_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kz_server_kz_server_kafka_secrets_volume
	fi
	
if [[ "package_kz_server_kz_server_kafka_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kz_server_kz_server_kafka_data_volume
	fi
	
if [[ "package_kz_server_kz_server_zookeeper_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kz_server_kz_server_zookeeper_secrets_volume
	fi
	
if [[ "package_kz_server_kz_server_zookeeper_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kz_server_kz_server_zookeeper_data_volume
	fi
	
if [[ "package_kz_server_kz_server_zookeeper_log_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_kz_server_kz_server_zookeeper_log_volume
	fi
	
