#!/usr/bin/env bash


prefix="package_$2"


executionplane --silent docker container prune --force

if [[ "_kafka_secrets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "_kafka_secrets_volume"
			result=$(docker volume ls | grep "_kafka_secrets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "_kafka_data_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "_kafka_data_volume"
			result=$(docker volume ls | grep "_kafka_data_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "_zookeeper_secrets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "_zookeeper_secrets_volume"
			result=$(docker volume ls | grep "_zookeeper_secrets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "_zookeeper_data_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "_zookeeper_data_volume"
			result=$(docker volume ls | grep "_zookeeper_data_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "_zookeeper_log_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "_zookeeper_log_volume"
			result=$(docker volume ls | grep "_zookeeper_log_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
